services:
    laravel.test:
        build:
            context: '.'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        image: laravel_app
        ports:
            - '${APP_PORT:-8080}:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            APP_ENV: local
            APP_DEBUG: 1
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            MONGO_DB_CONNECTION: mongodb
            MONGO_DB_HOST: mongo
            MONGO_DB_PORT: 27017
            MONGO_DB_DATABASE: laravel
            MONGO_DB_USERNAME: root
            MONGO_DB_PASSWORD: secret
        volumes:
            - '.:/var/www/html'
        working_dir: /var/www/html
        networks:
            - laravel-net
        depends_on:
            - mysql
            - mongo
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mongo:
        image: 'mongo:6.0'
        ports:
            - '${FORWARD_MONGO_PORT:-27017}:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'root'
            MONGO_INITDB_ROOT_PASSWORD: 'secret'
            MONGO_INITDB_DATABASE: 'laravel'
        volumes:
            - mongo-data:/data/db
        networks:
            - laravel-net
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    laravel-net:
        driver: bridge
volumes:
    mysql-data:
        driver: local
    mongo-data:
        driver: local
